### PR TITLE
Android 11 or higher

### PR DESCRIPTION
**Pull request by Osmar-Souza**
Improved the project to work on apis > 29

### CODE REVIEW

**Comment by FilipeMarch** [comment]
Hello, @Osmar-Souza, I've just seen your PR; I will take a look on it today and give you a feedback

**Comment by Osmar-Souza** [comment]
Hello, @FilipeMarch I hope I helped, it worked for me, I also thank you for your help by making your code available.

**Comment by FilipeMarch** [comment]
I tested it but it did not work on my device, Android 13.
It kept going to a permission files screen, it doesn't matter what I do there, nothing changes.

**Comment by Osmar-Souza** [comment]
then, when you enter the file permission screen, click on accept, after that click on the back button, with that you will return to the app, and you will be able to access your files

**Comment by FilipeMarch** [comment]
> then, when you enter the file permission screen, click on accept, after that click on the back button, with that you will return to the app, and you will be able to access your files

> it doesn't matter what I do there

Later I will update this repo with a method that works using SharedStorage

**Comment by FilipeMarch** [comment]
Hello, I updated the repository and now it works on all Android versions.
I'm closing this PR but I do appreciate your efforts! Thanks
If you need any help, please let me know.

**Pull request closed without merging**
